/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testservice.adventureworks2014.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testservice.adventureworks2014.VjobCandidateEducation;
import com.testservice.adventureworks2014.VjobCandidateEducationId;


/**
 * ServiceImpl object for domain model class VjobCandidateEducation.
 *
 * @see VjobCandidateEducation
 */
@Service("AdventureWorks2014.VjobCandidateEducationService")
public class VjobCandidateEducationServiceImpl implements VjobCandidateEducationService {

    private static final Logger LOGGER = LoggerFactory.getLogger(VjobCandidateEducationServiceImpl.class);


    @Autowired
    @Qualifier("AdventureWorks2014.VjobCandidateEducationDao")
    private WMGenericDao<VjobCandidateEducation, VjobCandidateEducationId> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<VjobCandidateEducation, VjobCandidateEducationId> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

	@Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
	@Override
	public VjobCandidateEducation getById(VjobCandidateEducationId vjobcandidateeducationId) throws EntityNotFoundException {
        LOGGER.debug("Finding VjobCandidateEducation by id: {}", vjobcandidateeducationId);
        VjobCandidateEducation vjobCandidateEducation = this.wmGenericDao.findById(vjobcandidateeducationId);
        if (vjobCandidateEducation == null){
            LOGGER.debug("No VjobCandidateEducation found with id: {}", vjobcandidateeducationId);
            throw new EntityNotFoundException(String.valueOf(vjobcandidateeducationId));
        }
        return vjobCandidateEducation;
    }

    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
	@Override
	public VjobCandidateEducation findById(VjobCandidateEducationId vjobcandidateeducationId) {
        LOGGER.debug("Finding VjobCandidateEducation by id: {}", vjobcandidateeducationId);
        return this.wmGenericDao.findById(vjobcandidateeducationId);
    }


	@Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
	@Override
	public Page<VjobCandidateEducation> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all VjobCandidateEducations");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
    @Override
    public Page<VjobCandidateEducation> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all VjobCandidateEducations");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service AdventureWorks2014 for table VjobCandidateEducation to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }



}

