/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testservice.adventureworks2014.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.testservice.adventureworks2014.Table13;
import com.testservice.adventureworks2014.service.Table13Service;

/**
 * Controller object for domain model class Table13.
 * @see Table13
 */
@RestController("AdventureWorks2014.Table13Controller")
@Api(value = "Table13Controller", description = "Exposes APIs to work with Table13 resource.")
@RequestMapping("/AdventureWorks2014/Table13")
public class Table13Controller {

    private static final Logger LOGGER = LoggerFactory.getLogger(Table13Controller.class);

    @Autowired
    @Qualifier("AdventureWorks2014.Table13Service")
    private Table13Service table13Service;

    @ApiOperation(value = "Creates a new Table13 instance.")
    @RequestMapping(method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Table13 createTable13(@RequestBody Table13 table13) {
        LOGGER.debug("Create Table13 with information: {}", table13);
        table13 = table13Service.create(table13);
        LOGGER.debug("Created Table13 with information: {}", table13);
        return table13;
    }

    @ApiOperation(value = "Returns the Table13 instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Table13 getTable13(@PathVariable("id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Getting Table13 with id: {}", id);
        Table13 foundTable13 = table13Service.getById(id);
        LOGGER.debug("Table13 details with id: {}", foundTable13);
        return foundTable13;
    }

    @ApiOperation(value = "Updates the Table13 instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.PUT)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Table13 editTable13(@PathVariable("id") Integer id, @RequestBody Table13 table13) throws EntityNotFoundException {
        LOGGER.debug("Editing Table13 with id: {}", table13.getId());
        table13.setId(id);
        table13 = table13Service.update(table13);
        LOGGER.debug("Table13 details with id: {}", table13);
        return table13;
    }

    @ApiOperation(value = "Deletes the Table13 instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.DELETE)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteTable13(@PathVariable("id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Deleting Table13 with id: {}", id);
        Table13 deletedTable13 = table13Service.delete(id);
        return deletedTable13 != null;
    }

    /**
     * @deprecated Use {@link #findTable13s(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of Table13 instances matching the search criteria.")
    @RequestMapping(value = "/search", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Table13> findTable13s(Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering Table13s list");
        return table13Service.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the list of Table13 instances matching the search criteria.")
    @RequestMapping(method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Table13> findTable13s(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Table13s list");
        return table13Service.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data.")
    @RequestMapping(value = "/export/{exportType}", method = RequestMethod.GET, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportTable13s(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        return table13Service.export(exportType, query, pageable);
    }

    @ApiOperation(value = "Returns the total count of Table13 instances.")
    @RequestMapping(value = "/count", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Long countTable13s(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
        LOGGER.debug("counting Table13s");
        return table13Service.count(query);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service Table13Service instance
	 */
    protected void setTable13Service(Table13Service service) {
        this.table13Service = service;
    }
}
